---
# vars for the django app
acserver_install_prefix: /usr/local
acserver_app_dir: "{{acserver_install_prefix}}/ACServerManager"
acserver_virtualenv: /var/lib/acserver
acserver_git_repo: https://github.com/PeteTheAutomator/ACServerManager.git

# vars for the assetto corsa dedicated server
acserver_server_install_prefix: /home/acserver
acserver_server_install_dir: "{{acserver_server_install_prefix}}/assetto-server"
acserver_server_config_dir: "{{acserver_server_install_dir}}/cfg"
acserver_server_plugins_dir: "{{acserver_server_install_dir}}/plugins"

# vars for stracker
acserver_stracker_bundle_url: http://www.n-e-y-s.de/downloads/stracker/stable/stracker-V3.2.10.zip
acserver_stracker_dir: "{{acserver_server_install_prefix}}/stracker"

# vars for minorating and mono
acserver_minorating_mono_repo: http://download.mono-project.com/repo/centos/
acserver_minorating_mono_repo_key: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
acserver_minorating_dir: "{{acserver_server_plugins_dir}}/minorating"
acserver_minorating_bundle_url: http://www.minorating.com/download/MinoRatingPlugin_1.4.3.zip
